name: Build Sing-box srs file
on:
  push:
    paths:
      - 'proxy.json'
  workflow_dispatch:
jobs:
  my_job:
    name: build sing-box srs file from proxy.json
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: run sing binary
        run: |
          ls -l
          ./sing-box rule-set compile --output sing_proxy.srs ./proxy.json
          git config --local user.name action-bot
          git config --local user.email action-bot@no-reply
          git add sing_proxy.srs
          git commit -m "update sing_proxy.srs"
          git push origin main
